package com.lihui.bean;

public class MajorInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_info.id
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_info.name
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_info.college_id
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    private Integer collegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_info.introduce
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    private String introduce;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_info.id
     *
     * @return the value of major_info.id
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_info.id
     *
     * @param id the value for major_info.id
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_info.name
     *
     * @return the value of major_info.name
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_info.name
     *
     * @param name the value for major_info.name
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_info.college_id
     *
     * @return the value of major_info.college_id
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public Integer getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_info.college_id
     *
     * @param collegeId the value for major_info.college_id
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public void setCollegeId(Integer collegeId) {
        this.collegeId = collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_info.introduce
     *
     * @return the value of major_info.introduce
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_info.introduce
     *
     * @param introduce the value for major_info.introduce
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }
}