package com.lihui.bean;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.college_id
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    private Integer collegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.major_id
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    private Integer majorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.alias
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.pass_word
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    private String passWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.image_url
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.name
     *
     * @param name the value for user_info.name
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.college_id
     *
     * @return the value of user_info.college_id
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public Integer getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.college_id
     *
     * @param collegeId the value for user_info.college_id
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public void setCollegeId(Integer collegeId) {
        this.collegeId = collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.major_id
     *
     * @return the value of user_info.major_id
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.major_id
     *
     * @param majorId the value for user_info.major_id
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.alias
     *
     * @return the value of user_info.alias
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.alias
     *
     * @param alias the value for user_info.alias
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.pass_word
     *
     * @return the value of user_info.pass_word
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.pass_word
     *
     * @param passWord the value for user_info.pass_word
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.image_url
     *
     * @return the value of user_info.image_url
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.image_url
     *
     * @param imageUrl the value for user_info.image_url
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}