package com.lihui.mapper;

import com.lihui.bean.ActivitiesInfo;

public interface ActivitiesInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities_info
     *
     * @mbggenerated
     */
    int insert(ActivitiesInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities_info
     *
     * @mbggenerated
     */
    int insertSelective(ActivitiesInfo record);
}