package com.lihui.mapper;

import com.lihui.bean.CollegeInfo;
import com.lihui.bean.CollegeInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollegeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int countByExample(CollegeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int deleteByExample(CollegeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int insert(CollegeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int insertSelective(CollegeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    List<CollegeInfo> selectByExampleWithBLOBs(CollegeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    List<CollegeInfo> selectByExample(CollegeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    CollegeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") CollegeInfo record, @Param("example") CollegeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") CollegeInfo record, @Param("example") CollegeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByExample(@Param("record") CollegeInfo record, @Param("example") CollegeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByPrimaryKeySelective(CollegeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CollegeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByPrimaryKey(CollegeInfo record);
}