package com.lihui.mapper;

import com.lihui.bean.CommunityInfo;
import com.lihui.bean.CommunityInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommunityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int countByExample(CommunityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int deleteByExample(CommunityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int insert(CommunityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int insertSelective(CommunityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    List<CommunityInfo> selectByExampleWithBLOBs(CommunityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    List<CommunityInfo> selectByExample(CommunityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    CommunityInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") CommunityInfo record, @Param("example") CommunityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") CommunityInfo record, @Param("example") CommunityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByExample(@Param("record") CommunityInfo record, @Param("example") CommunityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByPrimaryKeySelective(CommunityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CommunityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByPrimaryKey(CommunityInfo record);
}