package com.lihui.mapper;

import com.lihui.bean.CommunityInfo;

public interface CommunityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated
     */
    int insert(CommunityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated
     */
    int insertSelective(CommunityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated
     */
    CommunityInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommunityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CommunityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommunityInfo record);
}