package com.lihui.mapper;

import com.lihui.bean.MajorInfo;

public interface MajorInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated
     */
    int insert(MajorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated
     */
    int insertSelective(MajorInfo record);
}