package com.lihui.mapper;

import com.lihui.bean.MajorInfo;
import com.lihui.bean.MajorInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MajorInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int countByExample(MajorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int deleteByExample(MajorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int insert(MajorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int insertSelective(MajorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    List<MajorInfo> selectByExampleWithBLOBs(MajorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    List<MajorInfo> selectByExample(MajorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") MajorInfo record, @Param("example") MajorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") MajorInfo record, @Param("example") MajorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByExample(@Param("record") MajorInfo record, @Param("example") MajorInfoExample example);
}