package com.lihui.mapper;

import com.lihui.bean.UnivercityInfo;
import com.lihui.bean.UnivercityInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UnivercityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int countByExample(UnivercityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int deleteByExample(UnivercityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int insert(UnivercityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int insertSelective(UnivercityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    List<UnivercityInfo> selectByExampleWithBLOBs(UnivercityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    List<UnivercityInfo> selectByExample(UnivercityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    UnivercityInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") UnivercityInfo record, @Param("example") UnivercityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") UnivercityInfo record, @Param("example") UnivercityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByExample(@Param("record") UnivercityInfo record, @Param("example") UnivercityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByPrimaryKeySelective(UnivercityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(UnivercityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated Mon Jun 11 16:39:43 CST 2018
     */
    int updateByPrimaryKey(UnivercityInfo record);
}