package com.lihui.mapper;

import com.lihui.bean.UnivercityInfo;

public interface UnivercityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated
     */
    int insert(UnivercityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated
     */
    int insertSelective(UnivercityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated
     */
    UnivercityInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnivercityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(UnivercityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table univercity_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnivercityInfo record);
}